language: cpp
compiler:
    - gcc
sudo: false
addons:
    apt:
        packages:
        - lib32gcc-5-dev

script: 
    - mkdir ./build
    - chmod +x ./compile.sh && ./compile.sh ./build ./libffcall --host=i486-unknown-linux  CC="gcc -m32" CXX="g++ -m32"
