language: cpp
compiler:
    - gcc
sudo: false
addons:
    apt:
        packages:
        - lib32stdc++6
        - lib32z1-dev
        - libc6-dev-i386
        - linux-libc-dev
        
        - lib32gcc-5-dev
        - libgcc-5-dev
        - g++-5-multilib
        - gcc-5-multilib
        - g++-5
        - gcc-5
        
        sources:
        - ubuntu-toolchain-r-test

script: 
    - mkdir ./build
    - chmod +x ./compile.sh && ./compile.sh ./build ./libffcall --host=i486-unknown-linux  CC="gcc -m32" CXX="g++ -m32"
