language: cpp
compiler:
    - gcc
sudo: false
addons:
    apt:
        packages:
        - libc6-dev-i386

script: 
    - mkdir ./build
    - chmod +x ./compile.sh && ./compile.sh ./build ./libffcall --host=i486-unknown-linux  CC="gcc -m32" CXX="g++ -m32"
